const DEFAULT_PROMPT = 'Continúa autónomamente el desarrollo del proyecto desde el estado real más reciente. Antes de modificar nada: inspecciona el estado actual del repo, rama, issues, PRs, CI y revisiones. No te detengas después de cada paso; avanza mientras sea seguro, sin duplicar trabajo, y reporta solo hitos grandes.';
const PROMPT_SCHEMA_VERSION = 2;
const DEFAULTS = { prompt: DEFAULT_PROMPT, promptSchemaVersion: PROMPT_SCHEMA_VERSION, delaySeconds: 15, masterEnabled: false, followScroll: true, scrollStepMin: 90, scrollStepMax: 320, scrollPollMs: 220, scrollStableChecks: 8, scrollMaxSeconds: 45, manualScrollPauseSeconds: 20, autoReload: true, reloadCooldownMinutes: 2, periodicReload: false, periodicReloadMinutes: 30, reasoningLevel: 'high', conversationMode: 'chat' };
const extensionApi = globalThis.chrome || globalThis.browser;
const $ = id => document.getElementById(id);
const fields = { prompt: $('prompt'), delaySeconds: $('delay'), reasoningLevel: $('reasoning-level'), followScroll: $('follow-scroll'), scrollStepMin: $('step-min'), scrollStepMax: $('step-max'), scrollPollMs: $('poll-ms'), scrollStableChecks: $('stable-checks'), scrollMaxSeconds: $('max-seconds'), manualScrollPauseSeconds: $('manual-pause'), autoReload: $('auto-reload'), reloadCooldownMinutes: $('reload-cooldown'), periodicReload: $('periodic-reload'), periodicReloadMinutes: $('periodic-reload-minutes') };
const extensionVersion = extensionApi.runtime.getManifest().version;
let selectedConversationMode = 'chat';
$('version').textContent = `v${extensionVersion}`;
const apiCall = (fn, ...args) => new Promise((resolve, reject) => { try { const result = fn(...args, resolve); if (result?.then) result.then(resolve, reject); } catch (error) { reject(error); } });
async function activeTab(){ const tabs=await apiCall(extensionApi.tabs.query.bind(extensionApi.tabs),{active:true,currentWindow:true}); return tabs[0]; }
async function save(){ const values={prompt:fields.prompt.value.trim()||DEFAULT_PROMPT,promptSchemaVersion:PROMPT_SCHEMA_VERSION,delaySeconds:Math.max(5,Number(fields.delaySeconds.value)||15),reasoningLevel:fields.reasoningLevel.value,conversationMode:selectedConversationMode,followScroll:fields.followScroll.checked,scrollStepMin:Number(fields.scrollStepMin.value)||90,scrollStepMax:Number(fields.scrollStepMax.value)||320,scrollPollMs:Number(fields.scrollPollMs.value)||220,scrollStableChecks:Number(fields.scrollStableChecks.value)||8,scrollMaxSeconds:Number(fields.scrollMaxSeconds.value)||45,manualScrollPauseSeconds:Math.max(0,Number(fields.manualScrollPauseSeconds.value)||0),autoReload:fields.autoReload.checked,reloadCooldownMinutes:Math.max(1,Number(fields.reloadCooldownMinutes.value)||2),periodicReload:fields.periodicReload.checked,periodicReloadMinutes:Math.max(5,Number(fields.periodicReloadMinutes.value)||30)}; await apiCall(extensionApi.storage.local.set.bind(extensionApi.storage.local),values); }
function renderConversationMode(mode){selectedConversationMode=mode==='work'?'work':'chat';for(const value of ['chat','work']){const button=$(`mode-${value}`);const selected=value===selectedConversationMode;button.classList.toggle('selected',selected);button.setAttribute('aria-pressed',String(selected));}}
for(const mode of ['chat','work'])$(`mode-${mode}`).addEventListener('click',async()=>{renderConversationMode(mode);await apiCall(extensionApi.storage.local.set.bind(extensionApi.storage.local),{conversationMode:mode});});
async function matchingTabs(){ return apiCall(extensionApi.tabs.query.bind(extensionApi.tabs),{url:['https://chatgpt.com/*']}); }
async function broadcast(enabled){ const tabs=await matchingTabs(); await Promise.all(tabs.map(tab=>new Promise(resolve=>{ try{const result=extensionApi.tabs.sendMessage(tab.id,{type:'autopilot:set-enabled',enabled},()=>resolve());if(result?.then)result.then(resolve,resolve);}catch(_e){resolve();}}))); }
async function runtimeMessage(payload){ return apiCall(extensionApi.runtime.sendMessage.bind(extensionApi.runtime),payload); }
async function message(payload){ const tab=await activeTab(); if(!tab?.id||!String(tab.url||'').startsWith('https://chatgpt.com/')) throw new Error('Abre primero una pestaña de chatgpt.com'); return new Promise((resolve,reject)=>{try{extensionApi.tabs.sendMessage(tab.id,payload,response=>{const error=extensionApi.runtime.lastError;if(error)return reject(new Error('Recarga esta pestaña para cargar Autopilot'));if(!response)return reject(new Error('La pestaña no respondió; recárgala'));resolve(response);});}catch(_e){reject(new Error('Recarga esta pestaña para cargar Autopilot'));}}); }
function showStatus(text,enabled){const status=$('status');status.textContent=text;status.classList.toggle('active',enabled===true);status.classList.toggle('paused',enabled===false);}
async function refresh(){try{const result=await message({type:'autopilot:get-status'});showStatus(`${result.enabled?'ACTIVO':'PAUSADO'} · ${result.status}`,result.enabled);}catch(error){showStatus(`v${extensionVersion} · ${error.message}`);}}
const cleanSamples=(values,maximum)=>(Array.isArray(values)?values:[]).filter(value=>Number.isFinite(value)&&value>0&&value<=maximum);
const average=(values,maximum)=>{const clean=cleanSamples(values,maximum);return clean.length?clean.reduce((a,b)=>a+b,0)/clean.length:0;};
const percentile=(values,ratio,maximum)=>{const clean=cleanSamples(values,maximum).sort((a,b)=>a-b);return clean.length?clean[Math.min(clean.length-1,Math.floor(clean.length*ratio))]:0;};
const duration=ms=>ms?`${(ms/1000).toFixed(ms<10000?1:0)} s`:'—';
function renderLearning(data={}){const errors=Object.entries(data.errorsByCode||{}).sort((a,b)=>b[1]-a[1]);const actions=Object.entries(data.actionSuccess||{}).sort((a,b)=>b[1]-a[1]);$('cycles').textContent=data.cycles||0;$('recoveries').textContent=data.recoveries||0;$('failures').textContent=data.failures||0;const response=data.responseSamplesMs||[],startup=data.startupSamplesMs||[];$('learning-details').innerHTML=`<b>Inicio medio:</b> ${duration(average(startup,600000))} · <b>p90:</b> ${duration(percentile(startup,.9,600000))}<br><b>Respuesta media:</b> ${duration(average(response,21600000))} · <b>p90:</b> ${duration(percentile(response,.9,21600000))}<br><b>Errores:</b> ${errors.length?errors.slice(0,5).map(([k,v])=>`${k} (${v})`).join(', '):'ninguno'}<br><b>Recuperaciones exitosas:</b> ${actions.length?actions.slice(0,4).map(([k,v])=>`${k} (${v})`).join(', '):'aún sin datos'}`;}
function refreshLearning(){extensionApi.storage.local.get({learning:{}},values=>renderLearning(values.learning));}
$('start').addEventListener('click',async()=>{try{await save();await apiCall(extensionApi.storage.local.set.bind(extensionApi.storage.local),{masterEnabled:true});await broadcast(true);await refresh();}catch(error){$('status').textContent=error.message;}});
$('stop').addEventListener('click',async()=>{try{await apiCall(extensionApi.storage.local.set.bind(extensionApi.storage.local),{masterEnabled:false});await broadcast(false);await refresh();}catch(error){$('status').textContent=error.message;}});
async function copyText(text){try{await navigator.clipboard.writeText(text);return;}catch(_e){}const field=document.createElement('textarea');field.value=text;document.body.appendChild(field);field.select();document.execCommand('copy');field.remove();}
$('copy-log').addEventListener('click',async()=>{try{const result=await runtimeMessage({type:'autopilot:get-log'});await copyText(JSON.stringify({exportedAt:new Date().toISOString(),extensionVersion,learning:(await apiCall(extensionApi.storage.local.get.bind(extensionApi.storage.local),{learning:{}})).learning,entries:result.entries||[]},null,2));$('status').textContent=`DIAGNÓSTICO COPIADO · ${(result.entries||[]).length} eventos`;}catch(error){$('status').textContent=`No pude copiar: ${error.message}`;}});
$('clear-log').addEventListener('click',async()=>{try{await runtimeMessage({type:'autopilot:clear-log'});$('status').textContent='LOG BORRADO';}catch(error){$('status').textContent=`No pude borrar: ${error.message}`;}});
extensionApi.storage.local.get(DEFAULTS,values=>{const savedPrompt=String(values.prompt||'').trim();const valid=values.promptSchemaVersion===PROMPT_SCHEMA_VERSION&&savedPrompt.length>0;fields.prompt.value=valid?savedPrompt:DEFAULT_PROMPT;fields.delaySeconds.value=values.delaySeconds;fields.reasoningLevel.value=values.reasoningLevel||'high';renderConversationMode(values.conversationMode);fields.followScroll.checked=values.followScroll!==false;fields.scrollStepMin.value=values.scrollStepMin;fields.scrollStepMax.value=values.scrollStepMax;fields.scrollPollMs.value=values.scrollPollMs;fields.scrollStableChecks.value=values.scrollStableChecks;fields.scrollMaxSeconds.value=values.scrollMaxSeconds;fields.manualScrollPauseSeconds.value=values.manualScrollPauseSeconds;fields.autoReload.checked=values.autoReload!==false;fields.reloadCooldownMinutes.value=values.reloadCooldownMinutes;fields.periodicReload.checked=values.periodicReload===true;fields.periodicReloadMinutes.value=values.periodicReloadMinutes;showStatus(values.masterEnabled?'ACTIVO · todas las pestañas':'PAUSADO · todas las pestañas',values.masterEnabled);refreshLearning();refresh();});
extensionApi.storage.onChanged.addListener((changes,area)=>{if(area==='local'&&changes.learning)renderLearning(changes.learning.newValue||{});if(area==='local'&&changes.masterEnabled)showStatus(changes.masterEnabled.newValue?'ACTIVO · todas las pestañas':'PAUSADO · todas las pestañas',Boolean(changes.masterEnabled.newValue));});setInterval(refreshLearning,5000);
